config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/help'

  match 'comments/:comment_id/destroy', to: 'comments#destroy', via: 'delete', as: 'delete_comment'
  match 'comments/:comment_id/update_comment', to: 'comments#update', via: 'patch', as: 'update_comment'
  match 'posts/:post_id/new_comment', to: 'comments#create', via: 'post', as: 'new_comment'
  match 'posts/:post_id/new_comment/:parent_id', to: 'comments#create', via: 'post', as: 'new_child_comment'

  resources :posts
  get 'posts/new'
  get 'personal_blog/:name', to: 'posts#personal_blog', as: 'personal_blog'

  resources :users
  get 'users/new'

  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  has_many :children, class_name: 'Comment', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'Comment'

  validates :text, presence: true, length: { maximum: 860 }
  before_save :set_id_in_post


  def set_id_in_post
    return if self.persisted?
    max_id_in_post = Comment.where(post_id: self[:post_id]).maximum(:id_in_post)
    max_id_in_post ? self[:id_in_post] = max_id_in_post + 1 : self[:id_in_post] = 1
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :facecontrol

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(parent_id: params[:parent_id], post_id: params[:post_id], user_id: current_user.id,
                           text: comment_params[:text])
    if (params[:parent_id].nil? || Comment.find(params[:parent_id]).text) && @comment.save
      render json: { reload_page: false, new_comment: render_to_string(partial: 'comments/build_comments_tree',
        locals: {input_comments: [@comment]}), comment_id: @comment.id }
    else
      Rails.logger.debug "Trying to answer to deleted comment by user with id: #{current_user.id}\n"
      render json: { reload_page: true}
    end
  end

  def edit
    @comment = Comment.find params[:comment_id]
  end

  def update
    @comment = Comment.find params[:comment_id]
    if current_user.id == @comment.user.id && !@comment.text.nil? && @comment.update_attributes(comment_params)
      render json: {updated_at: @comment.updated_at.strftime('%I:%M %b %d %Y') }
    else
      render nothing: true
    end
  end

  def destroy
    @comment = Comment.find params[:comment_id]
    if current_user.id == @comment.user.id && @comment.update_attribute(:text, nil)
      render json: {result: 'success', deleted_at: @comment.updated_at.strftime('%I:%M %b %d %Y')}
    else
      render json: {result: 'failure'}
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:text)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_build_comments_tree.html.erb
<% def build_comments input_comments %>
<%
     input_comments.each do |comment| %>
        <div class="one_comment_tree">
          <h5 comment_id="<%= comment.id %>" id_in_post="<%= comment.id_in_post %>" class="base_comment">
            <b><%= "\##{comment.id_in_post}" %></b>
            <%= link_to comment.user.name.capitalize, users_path(comment.user), target: '_blank' %>

            <span class="created_at">
                        <%= 'posted at ' + comment.created_at.strftime('%I:%M %b %d %Y') %>
            </span>


            <div class="clear"></div>
            <div class="image_wrapper">
              <%= image_tag comment.user.avatar.url(:thumb) %>
            </div>

            <% if current_user.id == comment.user.id %>
                <%= form_for comment, url: update_comment_path(comment), remote: true, html: {class: 'edit_comment display_none'} do |f| %>
                    <%= f.text_area :text, placeholder: 'Write a comment', rows: 4, id: "comment_text_#{comment.id}" %>
                    <%= f.submit 'Save changes', class: 'btn btn-large btn-primary display_none', id: "update_comment_#{comment.id}" %>
                <% end %>
                </p>
            <% end %>

            <% unless comment.text %>
                <div class="deleted_comment_text">This comment was deleted and frozen.<br/>Function answer no longer
                  available for it.
                </div>
            <% else %>
                <div class="show_comment_text"><%= comment.text %></div>
            <% end %>
            <div class="clear"></div>

            <div class="updated_at">
              <% if comment.updated_at != comment.created_at %>
                  <%= (comment.text ? 'updated at ' : 'deleted at ') + comment.updated_at.strftime('%I:%M %b %d %Y') %>
              <% end %>
            </div>

            <% if comment.text %>
                <span class="answer after_delete_comment">Answer</span>
                <% if current_user.id == comment.user.id %>
                    <span class="edit_comment_button after_delete_comment"> Edit comment </span>
                    <span class="discard_changes display_none after_delete_comment">Discard changes</span>
                    <span class="artificial_save_changes_button display_none after_delete_comment"> Save changes </span>
                    <span class="delete_comment_button after_delete_comment">
                        <%= link_to 'Delete comment', delete_comment_path(comment), method: 'delete',
                            data: {confirm: 'Are you sure you want to delete this comment  ?'}, class: 'delete_comment', remote: true %>
                    </span>
                <% end %>
            <% end %>
          </h5>
          <% unless comment.children.empty? %>
              <div class="children_comments">
                <% build_comments comment.children %>
              </div>
          <% end %>
        </div>
    <% end %>
<% end %>

<% build_comments input_comments %>