config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/help'

  match 'comments/:comment_id/destroy', to: 'comments#destroy', via: 'delete', as: 'delete_comment'
  match 'comments/:comment_id/update_comment', to: 'comments#update', via: 'patch', as: 'update_comment'
  match 'posts/:post_id/new_comment', to: 'comments#create', via: 'post', as: 'new_comment'
  match 'posts/:post_id/new_comment/:parent_id', to: 'comments#create', via: 'post', as: 'new_child_comment'

  resources :posts
  get 'posts/new'
  get 'personal_blog/:name', to: 'posts#personal_blog', as: 'personal_blog'

  resources :users
  get 'users/new'

  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { maximum: 240 }
  validates :text, presence: true, length: { maximum: 860 }

  def short_text(length = 55)
  	result = self[:text][0, length]
  	self[:text].length > length ? "#{result}..." : result
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :facecontrol
  before_action :is_post_exist, only: [:destroy, :show, :edit, :update]


  def index
    @posts = Post.order(id: :desc).paginate(page: params[:page], per_page: 5)
  end

  def personal_blog
    @user = User.find_by name: params[:name]
    if @user
      @posts = @user.posts.order(id: :desc).paginate(page: params[:page], per_page: 5)
    else
      redirect_to posts_path
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find params[:id]
    @parent_comments = @post.comments.select {|comment| comment.parent.nil? }
    @new_comment = Comment.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes post_params
      flash[:success] = 'Post updated'
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find params[:id]
    if current_user.id == @post.user.id && @post.destroy
      respond_to do |format|
        format.json { render(json: {result: 'success'}) }
        format.html { redirect_to(posts_path) }
      end
    else
      respond_to do |format|
        format.json { render json: {result: 'failure'} }
        format.html { render('edit') }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :password_confirmation, :avatar)
  end

  def is_post_exist
    redirect_to posts_path unless Post.find_by id: params[:id]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<% provide(:title, 'Edit post') %>
<div class="row">
  <h1>Edit your post</h1>
  <%= link_to 'Click this to delete this post', post_path(@post), method: 'delete', class: 'delete_post' %>
</div>

<div class="row post_edit">
  <div class="span6 offset3">
    <%= form_for(@post) do |f| %>
        <%= render 'shared/error_messages', subject: @post %>

        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :text %>
        <%= f.text_area :text, rows: 14 %>

        <%= f.submit 'Save changes', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

<script>
    $("a.delete_post").click(function(){
        var confirm1 = confirm('Are you sure you want to delete selected post ?');
        if (confirm1 === true) {
            return confirm('Are you really sure, it can not be reverted ?');
        }
        return false;
    });
</script>

app/views/posts/index.html.erb
<% provide(:title, 'Posts') %>
<h1>Posts</h1>
<h4><%= link_to 'Create new post', posts_new_path %></h4>

<%= will_paginate %>

<ul class="posts">
  <% @posts.each do |post| %>
      <li class="post">
        <h3><%= link_to post.title.capitalize, post %></h3>
        <h5><%= link_to 'posted by ' + post.user.name.capitalize, post.user, target: '_blank' %>
            <%= 'at ' + post.created_at.strftime('%I:%M %d %b %Y') %>
        </h5>
        <h5><%= post.short_text %></h5>
        <% if post.updated_at != post.created_at %>
            <span class="updated_at"><%= 'updated at ' + post.updated_at.strftime('%I:%M %d %b %Y') %></span>
            <br/>
        <% end %>

        <%= link_to 'Edit post', edit_post_path(post) if post.user.id == current_user.id %>
        <%= link_to 'Delete post', post_path(post), method: 'delete', remote: true, class: 'delete_post' if post.user.id == current_user.id %>

      </li>
  <% end %>
</ul>

<%= will_paginate %>

<script>
  $("a.delete_post").click(function(){
      var confirm1 = confirm('Are you sure you want to delete selected post ?');
      if (confirm1 === true) {
          return confirm('Are you really sure, it can not be reverted ?');
      }
      return false;
  });

  $("a.delete_post").bind("ajax:complete", function(event, xhr, status){
      if(xhr.responseJSON['result'] === 'success')
      {
          $(this).parent().remove()
      }
  });
</script>

app/views/posts/new.html.erb
<% provide(:title, 'Create new post') %>
<h1>New post</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @post do |f| %>
        <%= render 'shared/error_messages', subject: @post %>

        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :text %>
        <%= f.text_area :text, rows: 7 %>

        <%= f.submit 'Create new post', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/posts/personal_blog.html.erb
<% provide(:title, 'Posts') %>
<h1><%= link_to @user.name.capitalize, @user, target: '_blank' %> Posts</h1>
<% if current_user.id == @user.id %>
    <h4><%= link_to 'Create new post', posts_new_path %></h4>
<% end %>

<%= will_paginate %>

<ul class="posts">
  <% @posts.each do |post| %>
      <li>
        <h3><%= link_to post.title.capitalize, post %></h3>
        <h5><%= link_to 'posted by ' + post.user.name.capitalize, post.user, target: '_blank' %>
          <%= 'at ' + post.created_at.strftime('%d %b %I:%M %Y') %>
        </h5>
        <h5><%= post.short_text %></h5>
        <% if post.updated_at != post.created_at %>
            <span class="updated_at"><%= 'updated at ' + post.updated_at.strftime('%I:%M %d %b %Y') %></span>
            <br/>
        <% end %>
        <%= link_to 'Edit post', edit_post_path(post) if post.user.id == current_user.id %>
        <%= link_to 'Delete post', post_path(post), method: 'delete', remote: true, class: 'delete_post' if post.user.id == current_user.id %>
      </li>
  <% end %>
</ul>

<%= will_paginate %>

<script>
    $("a.delete_post").click(function(){
        var confirm1 = confirm('Are you sure you want to delete selected post ?');
        if (confirm1 === true) {
            return confirm('Are you really sure, it can not be reverted ?');
        }
        return false;
    });

    $("a.delete_post").bind("ajax:complete", function(event, xhr, status){
        if(xhr.responseJSON['result'] === 'success')
        {
            $(this).parent().remove()
        }
    });
</script>

app/views/posts/show.html.erb
<% provide(:title, @post.title.capitalize ) %>
<h2> <%= @post.title.capitalize %></h2>
<% if current_user.id == @post.user.id %>
    <%= link_to 'Edit post', edit_post_path(@post) %>
<% end %>
<h5> <%= 'Posted by ' + @post.user.name.capitalize + ' at ' + @post.created_at.strftime('%I:%M %d %b %Y')%> </h5>
<h5><%= link_to @post.user.name.capitalize + ' personal blog', personal_blog_path(name: @post.user.name) %></h5>
<h4 class="post_text"><%= @post.text %><p class="default_answer"> Answer </p></h4>

<div class="comments">
    <%= render partial: 'comments/build_comments_tree', locals: {input_comments: @parent_comments}%>
</div>

<%= form_for @new_comment, url: new_comment_path(@post.id), remote: true do |f| %>
    <%= f.text_area :text, placeholder: 'Write a comment', rows: 4, id: 'new_comment_text'%>
    <%= f.submit 'Send', class: "btn btn-large btn-primary", id: 'send_comment' %>
<% end %>

<script>

$(document).ready(function(){
    $("#new_comment").submit(function(e){
        if(!$("#new_comment_text").val())
        {
            return false
        }
    });

    parent_id = null

    $("#new_comment").bind("ajax:complete", function(event, xhr, status){
        $("#new_comment").attr("action", default_action)
        if(!xhr.responseJSON['reload_page'])
        {
            if(parent_id)
            {
                children_comments = $("h5[comment_id=" + parent_id + "]").parent().find(".children_comments")
                if(children_comments.length)
                {
                    $("h5[comment_id=" + parent_id + "]").parent().find(".children_comments").first().append(xhr.responseJSON['new_comment'])
                }
                else
                {
                    wrapper = '<div class="children_comments">' + xhr.responseJSON['new_comment'] + '</div>'
                    $("h5[comment_id=" + parent_id + "]").parent().append(wrapper)
                }
            }
            else
            {
                $(".comments").append(xhr.responseJSON['new_comment'])
            }
            parent_id = null
            $("#new_comment").attr("action", default_action)
            $("#new_comment_text").attr("placeholder", "Write a comment" )
            $("#new_comment_text").val('')

            jQuery.scrollTo($("h5[comment_id=" + parent_id + "]").offset().top-70, 500)
        }
        else
        {
            alert("This comment was deleted.")
            jQuery.scrollTo($("h5[comment_id=" + parent_id+ "]").offset().top-70, 500)
            setTimeout(function(){
                location.reload()
            }, 1500)
        }
    });

    $(".delete_comment").bind("ajax:complete", function(event, xhr, status){
        if(xhr.responseJSON['result'] == 'success')
        {
            comment_text = $(this).parents().eq(2).find(".show_comment_text").first()
            $(this).parents().eq(2).find(".updated_at").first().html('deleted at ' + xhr.responseJSON['deleted_at'])
            comment_text.html('This comment was deleted and frozen.<br/>Function answer no longer available for it.')
            comment_text.removeClass("show_comment_text")
            comment_text.addClass("deleted_comment_text")
            $(this).parents().eq(2).find(".after_delete_comment").slice(0, 5).remove()
        }
        else
        {
            alert("Something goes wrong.\nWrite to administrator.")
        }
    });

    $(".edit_comment").bind("ajax:complete", function(event, xhr, status){
        $(this).parent().find(".updated_at").html('updated at ' + xhr.responseJSON['updated_at'])
    });

    default_action = $("#new_comment").attr("action")

    $(".answer").click(function(){
        id_in_post = $(this).parent().attr("id_in_post")
        parent_id = $(this).parent().attr("comment_id")
        $("#new_comment").attr("action", default_action + '/' + parent_id)
        $("#new_comment_text").attr("placeholder", "Write answer for #" + id_in_post + " comment")
        jQuery.scrollTo('#new_comment', 500);
    });

    $(".default_answer").click(function(){
        parent_id = null
        $("#new_comment").attr("action", default_action)
        $("#new_comment_text").attr("placeholder", "Write a comment" )
        jQuery.scrollTo('#new_comment', 500);
    });

    $(".edit_comment_button").click(function(){
        parent = $(this).parent()
        parent.find("form").removeClass('display_none')
        parent.find(".show_comment_text").addClass('display_none')
        parent.find(".edit_comment_button").addClass('display_none')
        parent.find(".artificial_save_changes_button").removeClass('display_none')
        parent.find(".discard_changes").removeClass('display_none')
    });
    $(".discard_changes").click(function(){
        parent = $(this).parent()
        parent.find("form").addClass('display_none')
        parent.find("textarea").val(parent.find(".show_comment_text").html())
        parent.find(".show_comment_text").removeClass('display_none')
        parent.find(".edit_comment_button").removeClass('display_none')
        parent.find(".artificial_save_changes_button").addClass('display_none')
        parent.find(".discard_changes").addClass('display_none')
    });

    $(".artificial_save_changes_button").click(function(){
        parent = $(this).parent()
        textarea = parent.find("textarea").val()
        if(textarea)
        {
            parent.find("input[type='submit']").click()
            parent.find("form").addClass('display_none')
            parent.find(".show_comment_text").removeClass('display_none')
            parent.find(".show_comment_text").html(textarea)
            parent.find(".edit_comment_button").removeClass('display_none')
            parent.find(".artificial_save_changes_button").addClass('display_none')
            parent.find(".discard_changes").addClass('display_none')
        }
        else
        {
            alert("You can not send empty comment.\nTo delete comment click Delete comment link.")
            parent.find("textarea").val(parent.find(".show_comment_text").html())
        }
    });

});

</script>