config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/help'

  match 'comments/:comment_id/destroy', to: 'comments#destroy', via: 'delete', as: 'delete_comment'
  match 'comments/:comment_id/update_comment', to: 'comments#update', via: 'patch', as: 'update_comment'
  match 'posts/:post_id/new_comment', to: 'comments#create', via: 'post', as: 'new_comment'
  match 'posts/:post_id/new_comment/:parent_id', to: 'comments#create', via: 'post', as: 'new_child_comment'

  resources :posts
  get 'posts/new'
  get 'personal_blog/:name', to: 'posts#personal_blog', as: 'personal_blog'

  resources :users
  get 'users/new'

  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Blog created by <%= link_to 'Andrushko Nicolay','https://ua.linkedin.com/pub/николай-андрушко/100/152/6b7' %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'SBlog', root_path, id: "logo" %>
      <nav>
        <ul class="nav nav-pills pull-right setup_nav">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "My Blog", personal_blog_path(name: current_user.name) %></li>
            <li><%= link_to "Blogs", posts_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Sign out", signout_path, method: "delete", data: { confirm: 'Are you sure you want to exit ?' } %></li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>


app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.png' %>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//cdn.jsdelivr.net/jquery.scrollto/2.1.2/jquery.scrollTo.min.js"></script>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>